{
 "title": "Jitsi Videobridge",
 "tags": [ "jitsi" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "JVB",
    "query": {
     "query": "label_values(jvb_bit_rate_download_kbps,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Conferences",
   "type": "timeseries",
   "description": "Number of Conferences (on the JVBs) with at least one sending endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance) (jvb_conferences{instance=~\"$JVB.*.*\"} - jvb_inactive_conferences{instance=~\"$JVB.*.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Endpoints",
   "type": "timeseries",
   "description": "number of local endpoints (not octo) which are in an active conference. This includes endpoints which are not sending audio or video, but are in an active conference (i.e. they are receive-only)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "jvb_local_active_endpoints{instance=~\"$JVB.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVB Stress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(instance) (jvb_stress_level_ratio{instance=~\"$JVB.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RTCP-RTT",
   "type": "timeseries",
   "description": "round-trip-time measured via RTCP averaged over all local endpoints with a valid RTT measurement in milliseconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(instance) (jvb_rtt_aggregate_ms{instance=~\"$JVB.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Loss",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance)(jvb_incoming_loss_ratio{instance=~\"$JVB.*\"})",
     "legendFormat": "incoming: {{instance}}"
    },
    {
     "expr": "sum by(instance)(jvb_outgoing_loss_ratio{instance=~\"$JVB.*\"})",
     "legendFormat": "outging: {{instance}}"
    }
   ]
  },
  {
   "title": "Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "sum by(instance)(jvb_bit_rate_download_kbps{instance=~\"$JVB.*\"})",
     "legendFormat": "{{instance}} incoming"
    },
    {
     "expr": "sum by(instance)(jvb_bit_rate_upload_kbps{instance=~\"$JVB.*\"})",
     "legendFormat": "{{instance}} outging"
    }
   ]
  },
  {
   "title": "Endpoints with >10% loss",
   "type": "timeseries",
   "description": "number of active endpoints that have more than 10% loss in the bridge->endpoint direction",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(instance)(jvb_endpoints_with_high_outgoing_loss{instance=~\"$JVB.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Octo-Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(instance)(jvb_octo_receive_bitrate_bps{instance=~\"$JVB.*\"})",
     "legendFormat": "incoming: {{instance}}"
    },
    {
     "expr": "sum by(instance)(jvb_octo_send_bitrate_bps{instance=~\"$JVB.*\"})",
     "legendFormat": "outging: {{instance}}"
    }
   ]
  },
  {
   "title": "Conferences by sizes",
   "type": "piechart",
   "description": "Number of Conferences with n-Participants. NOTE: Also includes inactive conferences (nobody is sending/receiving).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Conferences" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (size) (jvb_conference_sizes{instance=~\"$JVB.*\",size!=\"0\",size!=\"1\"})",
     "legendFormat": "{{size}} Participants"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (instance:node_network_receive_bytes_excluding_lo:rate5m{instance=~\"$JVB.*\"})",
     "legendFormat": "{{instance}}: in"
    },
    {
     "expr": "sum by(instance) (instance:node_network_transmit_bytes_excluding_lo:rate5m{instance=~\"$JVB.*\"})",
     "legendFormat": "{{instance}}: out"
    }
   ]
  },
  {
   "title": "JVB Traffic per hour",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) ( increase(jvb_bytes_sent_total{instance=~\"$JVB.*\"}[1h]) + increase(jvb_bytes_received_total{instance=~\"$JVB.*\"}[1h]) )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UDP Buffer Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_netstat_Udp_RcvbufErrors{instance=~\"$JVB.*\"}[5m]))",
     "legendFormat": "{{instance}}: in"
    },
    {
     "expr": "sum by(instance) (rate(node_netstat_Udp_SndbufErrors{instance=~\"$JVB.*\"}[5m]))",
     "legendFormat": "{{instance}}: out"
    }
   ]
  }
 ]
}